name: font_awesome_flutter
description: The Font Awesome Icon pack available as Flutter Icons. Provides 2000 additional icons to use in your apps.
maintainer: Michael Spiss (@michaelspiss)
repository: https://github.com/fluttercommunity/font_awesome_flutter
issue_tracker: https://github.com/fluttercommunity/font_awesome_flutter/issues
version: 10.10.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  recase: ^4.1.0
  args: ^2.6.0
  flutter_test:
    sdk: flutter
  version: ^3.0.2
  ansicolor: ^2.0.3
  flutter_lints: ^5.0.0
  pub_semver: ^2.1.5

flutter:
  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: lib/fonts/Font Awesome 7 Brands-Regular-400.otf
          weight: 400
    - family: FontAwesomeRegular
      fonts:
        - asset: lib/fonts/Font Awesome 7 Free-Regular-400.otf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: lib/fonts/Font Awesome 7 Free-Solid-900.otf
          weight: 900
#    - family: FontAwesomeLight
#      fonts:
#        - asset: lib/fonts/Font Awesome 7 Pro-Light-300.otf
#          weight: 300
#    - family: FontAwesomeThin
#      fonts:
#        - asset: lib/fonts/Font Awesome 7 Pro-Thin-100.otf
#          weight: 100
#    - family: FontAwesomeSharpThin
#      fonts:
#        - asset: lib/fonts/Font Awesome 7 Sharp-Thin-100.otf
#          weight: 100
#    - family: FontAwesomeSharpLight
#      fonts:
#        - asset: lib/fonts/Font Awesome 7 Sharp-Light-300.otf
#          weight: 300
#    - family: FontAwesomeSharpRegular
#      fonts:
#        - asset: lib/fonts/Font Awesome 7 Sharp-Regular-400.otf
#          weight: 400
#    - family: FontAwesomeSharpSolid
#      fonts:
#        - asset: lib/fonts/Font Awesome 7 Sharp-Solid-900.otf
#          weight: 900