name: font_awesome_flutter
description: The Font Awesome Icon pack available as Flutter Icons. Provides 2000 additional icons to use in your apps.
maintainer: Michael Spiss (@michaelspiss)
repository: https://github.com/fluttercommunity/font_awesome_flutter
issue_tracker: https://github.com/fluttercommunity/font_awesome_flutter/issues
version: 10.9.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  recase: ^4.1.0
  args: ^2.6.0
  flutter_test:
    sdk: flutter
  version: ^3.0.2
  ansicolor: ^2.0.3
  flutter_lints: ^5.0.0
  pub_semver: ^2.1.5

flutter:
  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: lib/fonts/fa-brands-400.ttf
          weight: 400
    - family: FontAwesomeRegular
      fonts:
        - asset: lib/fonts/fa-regular-400.ttf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: lib/fonts/fa-solid-900.ttf
          weight: 900
#    - family: FontAwesomeLight
#      fonts:
#        - asset: lib/fonts/fa-light-300.ttf
#          weight: 300
#    - family: FontAwesomeThin
#      fonts:
#        - asset: lib/fonts/fa-thin-100.ttf
#          weight: 100
#    - family: FontAwesomeSharpThin
#      fonts:
#        - asset: lib/fonts/fa-sharp-thin-100.ttf
#          weight: 100
#    - family: FontAwesomeSharpLight
#      fonts:
#        - asset: lib/fonts/fa-sharp-light-300.ttf
#          weight: 300
#    - family: FontAwesomeSharpRegular
#      fonts:
#        - asset: lib/fonts/fa-sharp-regular-400.ttf
#          weight: 400
#    - family: FontAwesomeSharpSolid
#      fonts:
#        - asset: lib/fonts/fa-sharp-solid-900.ttf
#          weight: 900
